version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: goredisfiber
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3333:3306"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "1111:6379"
    networks:
      - app-network



networks:
  app-network:


